/*!
 * Open Realtime Connectivity JavaScript Library
 *
 * Copyright 2011, IBT, SA
 *
 * ORTC is part of our framework and it's powered by the world's first Real-Time Web Platform by IBT
 *
 * Join our movement to transform the World Wide Web into the Real-Time Web!
 *
 * Interested in Real-Time technology? See what we can do for your business today.
 * 
 * Transform your old website into an exciting Real-Time experience!
 * 
 * Improve the interaction with your visitor to a level never seen before
 * and increase visitor recurrency and loyalty.
 *
 * Visit us at www.realtime.co and learn more.
 *
 * Date: Tue Fev 11 2014 v2.1.16 1248
 */
var IbtRealTimeSJType="IbtRealTimeSJ";function loadOrtcFactory(j,m){var a=new OrtcFactory(j);m(a,null)}function OrtcFactory(){this.createClient=function(){return new IbtRealTimeSJ}}
function OrtcError(j){this.code=j;switch(j){case 1:this.message="Was not possible to load the kaazing api";break;case 2:this.message="Was not possible to load the socket.io api";break;case 3:this.message="Is not possible to load more than one factory of each ORTC type";break;case 4:this.message="Unknown ORTC type";break;case 5:this.message="Pusher key is not defined";break;case 6:this.message="Was not possible to load the pusher api";break;default:this.message="Unknown error"}}
String.prototype.ortcTreatUrl=function(){var j=this;j&&(j=j.replace(/\s+/g,""),j.charAt(j.length-1)=="/"&&(j=j.substring(0,j.length-1)));return j};function ortcIsValidUrl(j){return/^\s*(http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?\s*$/.exec(j)?!0:!1}function ortcIsValidInput(j){return/^[\w-:\/\.]*$/.exec(j)?!0:!1}function ortcIsValidBoolean(j){return/^(true|false|0|1)$/.exec(j)?!0:!1}function ortcIsFunction(j){return typeof j=="function"?!0:!1}
function ortcIsString(j){return typeof j=="string"?!0:!1}var JSON;JSON||(JSON={});
(function(){function j(a,z){var q,u,s,n,p=l,o,h=z[a];h&&typeof h=="object"&&typeof h.toJSON=="function"&&(h=h.toJSON(a));typeof t=="function"&&(h=t.call(z,a,h));switch(typeof h){case "string":return m(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";l+=x;o=[];if(Object.prototype.toString.apply(h)==="[object Array]"){n=h.length;for(q=0;q<n;q+=1)o[q]=j(q,h)||"null";s=o.length===0?"[]":l?"[\n"+l+o.join(",\n"+l)+"\n"+p+"]":
"["+o.join(",")+"]";l=p;return s}if(t&&typeof t=="object"){n=t.length;for(q=0;q<n;q+=1)typeof t[q]=="string"&&(u=t[q],s=j(u,h),s&&o.push(m(u)+(l?": ":":")+s))}else for(u in h)Object.prototype.hasOwnProperty.call(h,u)&&(s=j(u,h),s&&o.push(m(u)+(l?": ":":")+s));s=o.length===0?"{}":l?"{\n"+l+o.join(",\n"+l)+"\n"+p+"}":"{"+o.join(",")+"}";l=p;return s}}function m(a){r.lastIndex=0;return r.test(a)?'"'+a.replace(r,function(a){var e=I[a];return typeof e=="string"?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function a(a){return a<10?"0"+a:a}typeof Date.prototype.toJSON!="function"&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var v=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
r=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,l,x,I={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},t;typeof JSON.stringify!="function"&&(JSON.stringify=function(a,m,q){var u;l="";x="";if(typeof q=="number")for(u=0;u<q;u+=1)x+=" ";else typeof q=="string"&&(x=q);t=m;if(!m||typeof m=="function"||typeof m=="object"&&typeof m.length=="number")return j("",{"":a});throw Error("JSON.stringify");
});typeof JSON.parse!="function"&&(JSON.parse=function(a,j){function m(a,e){var l,o,h=a[e];if(h&&typeof h=="object")for(l in h)Object.prototype.hasOwnProperty.call(h,l)&&(o=m(h,l),o!==void 0?h[l]=o:delete h[l]);return j.call(a,e,h)}var l;a=String(a);v.lastIndex=0;v.test(a)&&(a=a.replace(v,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return l=eval("("+a+")"),typeof j=="function"?m({"":l},""):l;throw new SyntaxError("JSON.parse");})})();
SockJS=function(){var j=document,m=window,a={},v=function(){};v.prototype.addEventListener=function(g,d){this._listeners||(this._listeners={});g in this._listeners||(this._listeners[g]=[]);var c=this._listeners[g];a.arrIndexOf(c,d)===-1&&c.push(d)};v.prototype.removeEventListener=function(g,d){if(this._listeners&&g in this._listeners){var c=this._listeners[g],b=a.arrIndexOf(c,d);b!==-1&&(c.length>1?this._listeners[g]=c.slice(0,b).concat(c.slice(b+1)):delete this._listeners[g])}};v.prototype.dispatchEvent=
function(g){var a=g.type,c=Array.prototype.slice.call(arguments,0);this["on"+a]&&this["on"+a].apply(this,c);if(this._listeners&&a in this._listeners)for(var b=0;b<this._listeners[a].length;b++)this._listeners[a][b].apply(this,c)};var r=function(g,a){this.type=g;if(typeof a!="undefined")for(var c in a)a.hasOwnProperty(c)&&(this[c]=a[c])};r.prototype.toString=function(){var g=[],a;for(a in this)if(this.hasOwnProperty(a)){var c=this[a];typeof c=="function"&&(c="[function]");g.push(a+"="+c)}return"SimpleEvent("+
g.join(", ")+")"};var l=function(g){this.events=g||[]};l.prototype.emit=function(g){var d=Array.prototype.slice.call(arguments,1);!this.nuked&&this["on"+g]&&this["on"+g].apply(this,d);a.arrIndexOf(this.events,g)===-1&&a.log("Event "+JSON.stringify(g)+" not listed "+JSON.stringify(this.events)+" in "+this)};l.prototype.nuke=function(){this.nuked=!0;for(var g=0;g<this.events.length;g++)delete this[this.events[g]]};a.random_string=function(g,a){var a=a||37,c,b=[];for(c=0;c<g;c++)b.push("abcdefghijklmnopqrstuvwxyz0123456789_".substr(Math.floor(Math.random()*
a),1));return b.join("")};a.random_number=function(g){return Math.floor(Math.random()*g)};a.random_number_string=function(g){var d=(""+(g-1)).length;return(Array(d+1).join("0")+a.random_number(g)).slice(-d)};a.getOrigin=function(g){g+="/";return g.split("/").slice(0,3).join("/")};a.isLocalUrl=function(g){var a=m.location.href.split("/").slice(0,3).join("/");return g.slice(0,a.length)===a};a.objectExtend=function(a,d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c]);return a};a.polluteGlobalNamespace=
function(){"_jp"in m||(m._jp={})};a.closeFrame=function(a,d){return"c"+JSON.stringify([a,d])};a.userSetCode=function(a){return a===1E3||a>=3E3&&a<=4999};a.countRTO=function(a){var d;return a>100?d=3*a:d=a+200,d};a.log=function(){m.console&&console.log&&console.log.apply&&console.log.apply(console,arguments)};a.bind=function(a,d){return a.bind?a.bind(d):function(){return a.apply(d,arguments)}};a.amendUrl=function(a){var d=j.location;if(!a)throw Error("Wrong url for SockJS");return a.indexOf("//")===
0&&(a=d.protocol+a),a.indexOf("/")===0&&(a=d.protocol+"//"+d.host+a),a=a.replace(/[/]+$/,""),a};a.arrIndexOf=function(a,d){for(var c=0;c<a.length;c++)if(a[c]===d)return c;return-1};a.arrSkip=function(g,d){var c=a.arrIndexOf(g,d);return c===-1?g.slice():g.slice(0,c).concat(g.slice(c+1))};a.isArray=Array.isArray||function(a){return{}.toString.call(a).indexOf("Array")>=0};a.delay=function(a,d){return typeof a=="function"&&(d=a,a=0),setTimeout(d,a)};var x=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
I={"\x00":"\\u0000","\u0001":"\\u0001","\u0002":"\\u0002","\u0003":"\\u0003","\u0004":"\\u0004","\u0005":"\\u0005","\u0006":"\\u0006","\u0007":"\\u0007","\u0008":"\\b","\t":"\\t","\n":"\\n","\u000b":"\\u000b","\u000c":"\\f","\r":"\\r","\u000e":"\\u000e","\u000f":"\\u000f","\u0010":"\\u0010","\u0011":"\\u0011","\u0012":"\\u0012","\u0013":"\\u0013","\u0014":"\\u0014","\u0015":"\\u0015","\u0016":"\\u0016","\u0017":"\\u0017","\u0018":"\\u0018","\u0019":"\\u0019","\u001a":"\\u001a","\u001b":"\\u001b",
"\u001c":"\\u001c","\u001d":"\\u001d","\u001e":"\\u001e","\u001f":"\\u001f",'"':'\\"',"\\":"\\\\","\u007f":"\\u007f","\u0080":"\\u0080","\u0081":"\\u0081","\u0082":"\\u0082","\u0083":"\\u0083","\u0084":"\\u0084","\u0085":"\\u0085","\u0086":"\\u0086","\u0087":"\\u0087","\u0088":"\\u0088","\u0089":"\\u0089","\u008a":"\\u008a","\u008b":"\\u008b","\u008c":"\\u008c","\u008d":"\\u008d","\u008e":"\\u008e","\u008f":"\\u008f","\u0090":"\\u0090","\u0091":"\\u0091","\u0092":"\\u0092","\u0093":"\\u0093","\u0094":"\\u0094",
"\u0095":"\\u0095","\u0096":"\\u0096","\u0097":"\\u0097","\u0098":"\\u0098","\u0099":"\\u0099","\u009a":"\\u009a","\u009b":"\\u009b","\u009c":"\\u009c","\u009d":"\\u009d","\u009e":"\\u009e","\u009f":"\\u009f","\u00ad":"\\u00ad","\u0600":"\\u0600","\u0601":"\\u0601","\u0602":"\\u0602","\u0603":"\\u0603","\u0604":"\\u0604","\u070f":"\\u070f","\u17b4":"\\u17b4","\u17b5":"\\u17b5","\u200c":"\\u200c","\u200d":"\\u200d","\u200e":"\\u200e","\u200f":"\\u200f","\u2028":"\\u2028","\u2029":"\\u2029","\u202a":"\\u202a",
"\u202b":"\\u202b","\u202c":"\\u202c","\u202d":"\\u202d","\u202e":"\\u202e","\u202f":"\\u202f","\u2060":"\\u2060","\u2061":"\\u2061","\u2062":"\\u2062","\u2063":"\\u2063","\u2064":"\\u2064","\u2065":"\\u2065","\u2066":"\\u2066","\u2067":"\\u2067","\u2068":"\\u2068","\u2069":"\\u2069","\u206a":"\\u206a","\u206b":"\\u206b","\u206c":"\\u206c","\u206d":"\\u206d","\u206e":"\\u206e","\u206f":"\\u206f","\ufeff":"\\ufeff","\ufff0":"\\ufff0","\ufff1":"\\ufff1","\ufff2":"\\ufff2","\ufff3":"\\ufff3","\ufff4":"\\ufff4",
"\ufff5":"\\ufff5","\ufff6":"\\ufff6","\ufff7":"\\ufff7","\ufff8":"\\ufff8","\ufff9":"\\ufff9","\ufffa":"\\ufffa","\ufffb":"\\ufffb","\ufffc":"\\ufffc","\ufffd":"\\ufffd","\ufffe":"\\ufffe","\uffff":"\\uffff"},t=/[\x00-\x1f\ud800-\udfff\ufffe\uffff\u0300-\u0333\u033d-\u0346\u034a-\u034c\u0350-\u0352\u0357-\u0358\u035c-\u0362\u0374\u037e\u0387\u0591-\u05af\u05c4\u0610-\u0617\u0653-\u0654\u0657-\u065b\u065d-\u065e\u06df-\u06e2\u06eb-\u06ec\u0730\u0732-\u0733\u0735-\u0736\u073a\u073d\u073f-\u0741\u0743\u0745\u0747\u07eb-\u07f1\u0951\u0958-\u095f\u09dc-\u09dd\u09df\u0a33\u0a36\u0a59-\u0a5b\u0a5e\u0b5c-\u0b5d\u0e38-\u0e39\u0f43\u0f4d\u0f52\u0f57\u0f5c\u0f69\u0f72-\u0f76\u0f78\u0f80-\u0f83\u0f93\u0f9d\u0fa2\u0fa7\u0fac\u0fb9\u1939-\u193a\u1a17\u1b6b\u1cda-\u1cdb\u1dc0-\u1dcf\u1dfc\u1dfe\u1f71\u1f73\u1f75\u1f77\u1f79\u1f7b\u1f7d\u1fbb\u1fbe\u1fc9\u1fcb\u1fd3\u1fdb\u1fe3\u1feb\u1fee-\u1fef\u1ff9\u1ffb\u1ffd\u2000-\u2001\u20d0-\u20d1\u20d4-\u20d7\u20e7-\u20e9\u2126\u212a-\u212b\u2329-\u232a\u2adc\u302b-\u302c\uaab2-\uaab3\uf900-\ufa0d\ufa10\ufa12\ufa15-\ufa1e\ufa20\ufa22\ufa25-\ufa26\ufa2a-\ufa2d\ufa30-\ufa6d\ufa70-\ufad9\ufb1d\ufb1f\ufb2a-\ufb36\ufb38-\ufb3c\ufb3e\ufb40-\ufb41\ufb43-\ufb44\ufb46-\ufb4e\ufff0-\uffff]/g,
e,z=JSON&&JSON.stringify||function(a){return x.lastIndex=0,x.test(a)&&(a=a.replace(x,function(a){return I[a]})),'"'+a+'"'},q=function(a){var d,c={},b=[];for(d=0;d<65536;d++)b.push(String.fromCharCode(d));return a.lastIndex=0,b.join("").replace(a,function(b){return c[b]="\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4),""}),a.lastIndex=0,c};a.quote=function(a){a=z(a);return t.lastIndex=0,t.test(a)?(e||(e=q(t)),a.replace(t,function(a){return e[a]})):a};var u="websocket,xdr-streaming,xhr-streaming,iframe-eventsource,iframe-htmlfile,xdr-polling,xhr-polling,iframe-xhr-polling,jsonp-polling".split(",");
a.probeProtocols=function(){for(var a={},d=0;d<u.length;d++){var c=u[d];a[c]=p[c]&&p[c].enabled()}return a};a.detectProtocols=function(a,d,c){var b={},i=[];d||(d=u);for(var f=0;f<d.length;f++){var k=d[f];b[k]=a[k]}var e=function(c){var a=c.shift();b[a]?i.push(a):c.length>0&&e(c)};return c.websocket!==!1&&e(["websocket"]),b["xdr-streaming"]&&!c.cookie_needed?i.push("xdr-streaming"):e(["xhr-streaming","iframe-eventsource","iframe-htmlfile"]),b["xdr-polling"]&&!c.cookie_needed?i.push("xdr-polling"):
e(["xhr-polling","iframe-xhr-polling","jsonp-polling"]),i};a.createHook=function(){var g="a"+a.random_string(8);if(!("_sockjs_global"in m)){var d={};m._sockjs_global=function(c){return c in d||(d[c]={id:c,del:function(){delete d[c]}}),d[c]}}return m._sockjs_global(g)};a.attachMessage=function(g){a.attachEvent("message",g)};a.attachEvent=function(a,d){typeof m.addEventListener!="undefined"?m.addEventListener(a,d,!1):(j.attachEvent("on"+a,d),m.attachEvent("on"+a,d))};a.detachMessage=function(g){a.detachEvent("message",
g)};a.detachEvent=function(a,d){typeof m.addEventListener!="undefined"?m.removeEventListener(a,d,!1):(j.detachEvent("on"+a,d),m.detachEvent("on"+a,d))};var s={};a.unload_add=function(g){var d=a.random_string(8);return s[d]=g,d};a.unload_del=function(a){a in s&&delete s[a]};a.attachEvent("unload",function(){for(var a in s)s[a]()});a.createIframe=function(g,d){var c=j.createElement("iframe"),b,i=function(){clearTimeout(b);try{c.onload=null}catch(a){}c.onerror=null},f=function(){c&&(i(),c.src="about:blank",
setTimeout(function(){c&&c.parentNode.removeChild(c);c=null},0),a.detachEvent("unload",f))};return c.src=g,c.style.display="none",c.style.position="absolute",c.onerror=function(){c&&(f(),d("onerror"))},c.onload=function(){clearTimeout(b);b=setTimeout(function(){c&&(f(),d("onload timeout"))},2E3)},j.body.appendChild(c),b=setTimeout(function(){c&&(f(),d("timeout"))},5E3),a.attachEvent("unload",f),{iframe:c,cleanup:f,loaded:i}};a.createHtmlfile=function(g,d){var c=new ActiveXObject("htmlfile"),b,i,f=
function(){clearTimeout(b)},k=function(){if(c){f();a.detachEvent("unload",k);try{i.src="about:blank"}catch(b){}i.parentNode.removeChild(i);i=c=null;CollectGarbage()}};c.open();c.write('<html><script>document.domain="'+document.domain+'";<\/script></html>');c.close();c.parentWindow._jp=m._jp;var e=c.createElement("div");return c.body.appendChild(e),i=c.createElement("iframe"),e.appendChild(i),i.src=g,b=setTimeout(function(){c&&(k(),d("timeout"))},5E3),a.attachEvent("unload",k),{iframe:i,cleanup:k,
loaded:f}};var n=a.XHRObject=function(g,d,c){var b=this;a.delay(function(){b._start(g,d,c)})};n.prototype=new l(["chunk","finish"]);n.prototype._start=function(g,d,c){var b=this;if(m.ActiveXObject){d+=(d.indexOf("?")===-1?"?":"&")+"t="+ +new Date;try{b.xhr=new ActiveXObject("Microsoft.XMLHTTP")}catch(i){}}b.xhr||(b.xhr=new XMLHttpRequest);b.unload_ref=a.unload_add(function(){b._cleanup(!0)});try{b.xhr.open(g,d,!0)}catch(f){b.emit("finish",0,"");b._cleanup();return}"withCredentials"in b.xhr&&(b.xhr.withCredentials=
"true");b.xhr.onreadystatechange=function(){if(b.xhr){var c=b.xhr;switch(c.readyState){case 3:try{b.emit("chunk",c.status,c.responseText)}catch(a){}break;case 4:b.emit("finish",c.status,c.responseText),b._cleanup(!1)}}};b.xhr.send(c)};n.prototype._cleanup=function(g){if(this.xhr){a.unload_del(this.unload_ref);this.xhr.onreadystatechange=function(){};if(g)try{this.xhr.abort()}catch(d){}this.unload_ref=this.xhr=null}};n.prototype.close=function(){this.nuke();this._cleanup(!0)};n=a.XDRObject=function(g,
d,c){var b=this;a.delay(function(){b._start(g,d,c)})};n.prototype=new l(["chunk","finish"]);n.prototype._start=function(g,d,c){var b=this,i=new XDomainRequest;d+=(d.indexOf("?")===-1?"?":"&")+"t="+ +new Date;var f=i.ontimeout=i.onerror=function(){b.emit("finish",0,"");b._cleanup(!1)};i.onprogress=function(){b.emit("chunk",200,i.responseText)};i.onload=function(){b.emit("finish",200,i.responseText);b._cleanup(!1)};b.xdr=i;b.unload_ref=a.unload_add(function(){b._cleanup(!0)});try{b.xdr.open(g,d),b.xdr.send(c)}catch(k){f()}};
n.prototype._cleanup=function(g){if(this.xdr){a.unload_del(this.unload_ref);this.xdr.ontimeout=this.xdr.onerror=this.xdr.onprogress=this.xdr.onload=null;if(g)try{this.xdr.abort()}catch(d){}this.unload_ref=this.xdr=null}};n.prototype.close=function(){this.nuke();this._cleanup(!0)};a.isXHRCorsCapable=function(){return m.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest?1:m.XDomainRequest?2:w.enabled()?3:4};var p=function(g,d,c){var b=this,i;b._options={devel:!1,debug:!1,protocols_whitelist:[],
info:void 0,rtt:void 0};c&&a.objectExtend(b._options,c);b._base_url=a.amendUrl(g);b._server=b._options.server||a.random_number_string(1E3);b._options.protocols_whitelist&&b._options.protocols_whitelist.length?i=b._options.protocols_whitelist:(typeof d=="string"&&d.length>0?i=[d]:a.isArray(d)?i=d:i=null,i&&b._debug('Deprecated API: Use "protocols_whitelist" option instead of supplying protocol list as a second parameter to SockJS constructor.'));b._protocols=[];b.protocol=null;b.readyState=p.CONNECTING;
L(b._base_url).onfinish=function(c,a){c?(b._options.info&&(c=b._options.info),b._options.rtt&&(a=b._options.rtt),b._applyInfo(c,a,i),b._didClose()):b._didClose(1002,"Can't connect to server",!0)}};p.prototype=new v;p.version="0.2.1";p.CONNECTING=0;p.OPEN=1;p.CLOSING=2;p.CLOSED=3;p.prototype._debug=function(){this._options.debug&&a.log.apply(a,arguments)};p.prototype._dispatchOpen=function(){this.readyState===p.CONNECTING?(this._transport_tref&&(clearTimeout(this._transport_tref),this._transport_tref=
null),this.readyState=p.OPEN,this.dispatchEvent(new r("open"))):this._didClose(1006,"Server lost session")};p.prototype._dispatchMessage=function(a){this.readyState===p.OPEN&&this.dispatchEvent(new r("message",{data:a}))};p.prototype._dispatchHeartbeat=function(){this.readyState===p.OPEN&&this.dispatchEvent(new r("heartbeat",{}))};p.prototype._didClose=function(g,d,c){var b=this;if(b.readyState!==p.CONNECTING&&b.readyState!==p.OPEN&&b.readyState!==p.CLOSING)throw Error("INVALID_STATE_ERR");b._transport&&
b._transport.doCleanup();b._transport=null;var i=new r("close",{code:g,reason:d,wasClean:a.userSetCode(g)});if(!a.userSetCode(g)&&b.readyState===p.CONNECTING&&!c){if(b._try_next_protocol(i))return;i=new r("close",{code:2E3,reason:"All transports failed",wasClean:!1,last_event:i})}b.readyState=p.CLOSED;a.delay(function(){b.dispatchEvent(i)})};p.prototype._didMessage=function(a){switch(a.slice(0,1)){case "o":this._dispatchOpen();break;case "a":for(var a=JSON.parse(a.slice(1)||"[]"),d=0;d<a.length;d++)this._dispatchMessage(a[d]);
break;case "m":a=JSON.parse(a.slice(1)||"null");this._dispatchMessage(a);break;case "c":a=JSON.parse(a.slice(1)||"[]");this._didClose(a[0],a[1]);break;case "h":this._dispatchHeartbeat()}};p.prototype._try_next_protocol=function(g){var d=this;for(d.protocol&&(d._debug("Closed transport:",d.protocol,""+g),d.protocol=null),d._transport_tref&&(clearTimeout(d._transport_tref),d._transport_tref=null);;){g=d.protocol=d._protocols.shift();if(!g)return!1;if(p[g]&&p[g].need_body===!0&&!j.body)return d._protocols.unshift(g),
d.protocol="waiting-for-load",a.attachEvent("load",function(){d._try_next_protocol()}),!0;if(!p[g]||!p[g].enabled(d._options))d._debug("Skipping transport:",g);else{d._transport_tref=a.delay((d._options.rto||0)*(p[g].roundTrips||1)||5E3,function(){d.readyState===p.CONNECTING&&d._didClose(2007,"Transport timeouted")});var c=a.random_string(8),c=d._base_url+"/"+d._server+"/"+c;return d._debug("Opening transport:",g," url:"+c," RTO:"+d._options.rto),d._transport=new p[g](d,c,d._base_url),!0}}};p.prototype.close=
function(g,d){if(g&&!a.userSetCode(g))throw Error("INVALID_ACCESS_ERR");return this.readyState!==p.CONNECTING&&this.readyState!==p.OPEN?!1:(this.readyState=p.CLOSING,this._didClose(g||1E3,d||"Normal closure"),!0)};p.prototype.send=function(g){if(this.readyState===p.CONNECTING)throw Error("INVALID_STATE_ERR");return this.readyState===p.OPEN&&this._transport.doSend(a.quote(""+g)),!0};p.prototype._applyInfo=function(g,d,c){this._options.info=g;this._options.rtt=d;this._options.rto=a.countRTO(d);d=a.probeProtocols();
this._protocols=a.detectProtocols(d,c,g)};n=p.websocket=function(g,d){var c=this,b=d+"/websocket";b.slice(0,5)==="https"?b="wss"+b.slice(5):b="ws"+b.slice(4);c.ri=g;c.url=b;c.ws=new (m.WebSocket||m.MozWebSocket)(c.url);c.ws.onmessage=function(b){c.ri._didMessage(b.data)};c.unload_ref=a.unload_add(function(){c.ws.close()});c.ws.onclose=function(){c.ri._didMessage(a.closeFrame(1006,"WebSocket connection broken"))}};n.prototype.doSend=function(a){this.ws.send(a)};n.prototype.doCleanup=function(){var g=
this.ws;g&&(g.onmessage=g.onclose=null,g.close(),a.unload_del(this.unload_ref),this.unload_ref=this.ri=this.ws=null)};n.enabled=function(){return!!m.WebSocket||!!m.MozWebSocket};var o=function(){};o.prototype.send_constructor=function(a){this.send_buffer=[];this.sender=a};o.prototype.doSend=function(a){this.send_buffer.push(a);this.send_stop||this.send_schedule()};o.prototype.send_schedule_wait=function(){var g=this,d;g.send_stop=function(){g.send_stop=null;clearTimeout(d)};d=a.delay(25,function(){g.send_stop=
null;g.send_schedule()})};o.prototype.send_schedule=function(){var a=this;if(a.send_buffer.length>0){var d="["+a.send_buffer.join(",")+"]";a.send_stop=a.sender(a.trans_url,d,function(){a.send_stop=null;a.send_schedule_wait()});a.send_buffer=[]}};o.prototype.send_destructor=function(){this._send_stop&&this._send_stop();this._send_stop=null};var h=function(g,d,c){if(!("_send_form"in this)){var b=this._send_form=j.createElement("form"),i=this._send_area=j.createElement("textarea");i.name="d";b.style.display=
"none";b.style.position="absolute";b.method="POST";b.enctype="application/x-www-form-urlencoded";b.acceptCharset="UTF-8";b.appendChild(i);j.body.appendChild(b)}var b=this._send_form,i=this._send_area,f="a"+a.random_string(8);b.target=f;b.action=g+"/jsonp_send?i="+f;var k;try{k=j.createElement('<iframe name="'+f+'">')}catch(e){k=j.createElement("iframe"),k.name=f}k.id=f;b.appendChild(k);k.style.display="none";try{i.value=d}catch(h){alert("Your browser is seriously broken. Go home! "+h.message)}b.submit();
var Q=function(){if(k.onerror)k.onreadystatechange=k.onerror=k.onload=null,a.delay(500,function(){k.parentNode.removeChild(k);k=null}),i.value=null,c()};return k.onerror=k.onload=Q,k.onreadystatechange=function(){k.readyState=="complete"&&Q()},Q},y=function(a){return function(d,c,b){return(new a("POST",d+"/xhr_send",c)).onfinish=function(c){b(c)},function(c){b(0,c)}}},J=function(g,d){var c,b=j.createElement("script"),i,f=function(a){i&&(i.parentNode.removeChild(i),i=null);b&&(clearTimeout(c),b.parentNode.removeChild(b),
b.onreadystatechange=b.onerror=b.onload=b.onclick=null,b=null,d(a),d=null)},k=!1,e=null;b.id="a"+a.random_string(8);b.src=g;b.type="text/javascript";b.charset="UTF-8";b.onerror=function(){e||(e=setTimeout(function(){k||f(a.closeFrame(1006,"JSONP script loaded abnormally (onerror)"))},1E3))};b.onload=function(){f(a.closeFrame(1006,"JSONP script loaded abnormally (onload)"))};b.onreadystatechange=function(){if(/loaded|closed/.test(b.readyState)){if(b&&b.htmlFor&&b.onclick){k=!0;try{b.onclick()}catch(c){}}b&&
f(a.closeFrame(1006,"JSONP script loaded abnormally (onreadystatechange)"))}};if(typeof b.async=="undefined"&&j.attachEvent)if(/opera/i.test(navigator.userAgent))i=j.createElement("script"),i.text="try{var a = document.getElementById('"+b.id+"'); if(a)a.onerror();}catch(x){};",b.async=i.async=!1;else{try{b.htmlFor=b.id,b.event="onclick"}catch(h){}b.async=!0}typeof b.async!="undefined"&&(b.async=!0);c=setTimeout(function(){f(a.closeFrame(1006,"JSONP script loaded abnormally (timeout)"))},35E3);var Q=
j.getElementsByTagName("head")[0];return Q.insertBefore(b,Q.firstChild),i&&Q.insertBefore(i,Q.firstChild),f},n=p["jsonp-polling"]=function(g,d){a.polluteGlobalNamespace();this.ri=g;this.trans_url=d;this.send_constructor(h);this._schedule_recv()};n.prototype=new o;n.prototype._schedule_recv=function(){var a=this;a._recv_stop=C(a.trans_url+"/jsonp",J,function(d){a._recv_stop=null;d&&(a._is_closing||a.ri._didMessage(d));a._is_closing||a._schedule_recv()})};n.enabled=function(){return!0};n.need_body=
!0;n.prototype.doCleanup=function(){this._is_closing=!0;this._recv_stop&&this._recv_stop();this.ri=this._recv_stop=null;this.send_destructor()};var C=function(g,d,c){var b="a"+a.random_string(6),g=g+"?c="+escape("_jp."+b),d=d(g,function(a){delete m._jp[b];c(a)});m._jp[b]=d;return function(){m._jp[b]&&m._jp[b](a.closeFrame(1E3,"JSONP user aborted read"))}},n=function(){};n.prototype=new o;n.prototype.run=function(a,d,c,b,i){this.ri=a;this.trans_url=d;this.send_constructor(y(i));this.poll=new N(a,b,
d+c,i)};n.prototype.doCleanup=function(){this.poll&&(this.poll.abort(),this.poll=null)};var G=p["xhr-streaming"]=function(g,d){this.run(g,d,"/xhr_streaming",E,a.XHRObject)};G.prototype=new n;G.enabled=function(){return m.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest};G.roundTrips=2;o=p["xdr-streaming"]=function(g,d){this.run(g,d,"/xhr_streaming",E,a.XDRObject)};o.prototype=new n;o.enabled=function(){return!!m.XDomainRequest};o.roundTrips=2;var R=p["xhr-polling"]=function(g,d){this.run(g,
d,"/xhr",E,a.XHRObject)};R.prototype=new n;R.enabled=G.enabled;R.roundTrips=2;G=p["xdr-polling"]=function(g,d){this.run(g,d,"/xhr",E,a.XDRObject)};G.prototype=new n;G.enabled=o.enabled;G.roundTrips=2;var w=function(){};w.prototype.i_constructor=function(g,d,c){var b=this;b.ri=g;b.origin=a.getOrigin(c);b.base_url=c;b.trans_url=d;g=c+"/iframe.html";b.ri._options.devel&&(g+="?t="+ +new Date);b.window_id=a.random_string(8);g+="#"+b.window_id;b.iframeObj=a.createIframe(g,function(c){b.ri._didClose(1006,
"Unable to load an iframe ("+c+")")});b.onmessage_cb=a.bind(b.onmessage,b);a.attachMessage(b.onmessage_cb)};w.prototype.doCleanup=function(){if(this.iframeObj){a.detachMessage(this.onmessage_cb);try{this.iframeObj.iframe.contentWindow&&this.postMessage("c")}catch(g){}this.iframeObj.cleanup();this.iframeObj=null;this.onmessage_cb=this.iframeObj=null}};w.prototype.onmessage=function(a){if(a.origin===this.origin){var d=a.data.slice(0,8),c=a.data.slice(8,9),a=a.data.slice(9);if(d===this.window_id)switch(c){case "s":this.iframeObj.loaded();
this.postMessage("s",JSON.stringify([p.version,this.protocol,this.trans_url,this.base_url]));break;case "t":this.ri._didMessage(a)}}};w.prototype.postMessage=function(a,d){this.iframeObj.iframe.contentWindow.postMessage(this.window_id+a+(d||""),this.origin)};w.prototype.doSend=function(a){this.postMessage("m",a)};w.enabled=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.indexOf("Konqueror")!==-1;return(typeof m.postMessage=="function"||typeof m.postMessage=="object")&&!a};var O,
A=function(g,d){parent!==m?parent.postMessage(O+g+(d||""),"*"):a.log("Can't postMessage, no parent window.",g,d)},B=function(){};B.prototype._didClose=function(g,d){A("t",a.closeFrame(g,d))};B.prototype._didMessage=function(a){A("t",a)};B.prototype._doSend=function(a){this._transport.doSend(a)};B.prototype._doCleanup=function(){this._transport.doCleanup()};p.bootstrap_iframe=function(){var e;O=j.location.hash.slice(1);a.attachMessage(function(d){if(d.source===parent){var c=d.data.slice(0,8),b=d.data.slice(8,
9),d=d.data.slice(9);if(c===O)switch(b){case "s":var i=JSON.parse(d),c=i[0],b=i[1],d=i[2],i=i[3];c!==p.version&&a.log('Incompatibile SockJS! Main site uses: "'+c+'", the iframe: "'+p.version+'".');if(!a.isLocalUrl(d)||!a.isLocalUrl(i)){a.log("Can't connect to different domain from within an iframe. ("+JSON.stringify([m.location.href,d,i])+")");break}e=new B;e._transport=new B[b](e,d,i);break;case "m":e._doSend(d);break;case "c":e&&e._doCleanup(),e=null}}});A("s")};var F=function(e,d){var c=this;a.delay(function(){c.doXhr(e,
d)})};F.prototype=new l(["finish"]);F.prototype.doXhr=function(e,d){var c=this,b=(new Date).getTime(),i=new d("GET",e+"/info",null),f=a.delay(8E3,function(){i.ontimeout()});i.onfinish=function(a,i){clearTimeout(f);f=null;if(a===200){var d=(new Date).getTime()-b,e=JSON.parse(i);typeof e!="object"&&(e={});c.emit("finish",e,d)}else c.emit("finish")};i.ontimeout=function(){i.close();c.emit("finish")}};var D=function(e){var d=this,c=function(){var c=new w;c.protocol="w-iframe-info-receiver";var a=function(a){typeof a==
"string"&&a.substr(0,1)==="m"?(a=JSON.parse(a.substr(1)),d.emit("finish",a[0],a[1])):d.emit("finish");c.doCleanup();c=null};c.i_constructor({_options:{},_didClose:a,_didMessage:a},e,e)};j.body?c():a.attachEvent("load",c)};D.prototype=new l(["finish"]);var H=function(){var e=this;a.delay(function(){e.emit("finish",{},2E3)})};H.prototype=new l(["finish"]);var L=function(e){if(a.isLocalUrl(e))return new F(e,a.XHRObject);switch(a.isXHRCorsCapable()){case 1:return new F(e,a.XHRObject);case 2:return new F(e,
a.XDRObject);case 3:return new D(e);default:return new H}};(B["w-iframe-info-receiver"]=function(e,d,c){(new F(c,a.XHRObject)).onfinish=function(c,a){e._didMessage("m"+JSON.stringify([c,a]));e._didClose()}}).prototype.doCleanup=function(){};l=p["iframe-eventsource"]=function(){this.protocol="w-iframe-eventsource";this.i_constructor.apply(this,arguments)};l.prototype=new w;l.enabled=function(){return"EventSource"in m&&w.enabled()};l.need_body=!0;l.roundTrips=3;(B["w-iframe-eventsource"]=function(e,
d){this.run(e,d,"/eventsource",P,a.XHRObject)}).prototype=new n;l=p["iframe-xhr-polling"]=function(){this.protocol="w-iframe-xhr-polling";this.i_constructor.apply(this,arguments)};l.prototype=new w;l.enabled=function(){return m.XMLHttpRequest&&w.enabled()};l.need_body=!0;l.roundTrips=3;(B["w-iframe-xhr-polling"]=function(e,d){this.run(e,d,"/xhr",E,a.XHRObject)}).prototype=new n;l=p["iframe-htmlfile"]=function(){this.protocol="w-iframe-htmlfile";this.i_constructor.apply(this,arguments)};l.prototype=
new w;l.enabled=function(){return w.enabled()};l.need_body=!0;l.roundTrips=3;(B["w-iframe-htmlfile"]=function(e,d){this.run(e,d,"/htmlfile",M,a.XHRObject)}).prototype=new n;var N=function(a,d,c,b){this.ri=a;this.Receiver=d;this.recv_url=c;this.AjaxObject=b;this._scheduleRecv()};N.prototype._scheduleRecv=function(){var a=this,d=a.poll=new a.Receiver(a.recv_url,a.AjaxObject),c=0;d.onmessage=function(b){c+=1;a.ri._didMessage(b.data)};d.onclose=function(c){var b;a.poll=(b=d.onmessage=d.onclose=null,d=
b);a.poll_is_closing||(c.reason==="permanent"?a.ri._didClose(1006,"Polling error ("+c.reason+")"):a._scheduleRecv())}};N.prototype.abort=function(){this.poll_is_closing=!0;this.poll&&this.poll.abort()};var P=function(e){var d=this,c=new EventSource(e);c.onmessage=function(c){d.dispatchEvent(new r("message",{data:unescape(c.data)}))};d.es_close=c.onerror=function(b,i){var f=i?"user":c.readyState!==2?"network":"permanent";d.es_close=c.onmessage=c.onerror=null;c.close();c=null;a.delay(200,function(){d.dispatchEvent(new r("close",
{reason:f}))})}};P.prototype=new v;P.prototype.abort=function(){this.es_close&&this.es_close({},!0)};var K,M=function(e){var d=this;a.polluteGlobalNamespace();d.id="a"+a.random_string(6,26);e+=(e.indexOf("?")===-1?"?":"&")+"c="+escape("_jp."+d.id);if(K===void 0)if("ActiveXObject"in m)try{K=!!new ActiveXObject("htmlfile")}catch(c){}else K=!1;var b=K?a.createHtmlfile:a.createIframe,i;m._jp[d.id]={start:function(){i.loaded()},message:function(c){d.dispatchEvent(new r("message",{data:c}))},stop:function(){d.iframe_close({},
"network")}};d.iframe_close=function(c,a){i.cleanup();d.iframe_close=i=null;delete m._jp[d.id];d.dispatchEvent(new r("close",{reason:a}))};i=b(e,function(){d.iframe_close({},"permanent")})};M.prototype=new v;M.prototype.abort=function(){this.iframe_close&&this.iframe_close({},"user")};var E=function(a,d){var c=this,b=0;c.xo=new d("POST",a,null);c.xo.onchunk=function(a,f){if(a===200)for(;;){var k=f.slice(b),d=k.indexOf("\n");if(d===-1)break;b+=d+1;k=k.slice(0,d);c.dispatchEvent(new r("message",{data:k}))}};
c.xo.onfinish=function(a,b){c.xo.onchunk(a,b);c.xo=null;c.dispatchEvent(new r("close",{reason:a===200?"network":"permanent"}))}};return E.prototype=new v,E.prototype.abort=function(){this.xo&&(this.xo.close(),this.dispatchEvent(new r("close",{reason:"user"})),this.xo=null)},p.getUtils=function(){return a},p.getIframeTransport=function(){return w},p}();"_sockjs_onload"in window&&setTimeout(_sockjs_onload,1);JSON||(JSON={});
(function(){function j(a,r){var q,u,s,n,p=l,o,h=r[a];h&&typeof h=="object"&&typeof h.toJSON=="function"&&(h=h.toJSON(a));typeof t=="function"&&(h=t.call(r,a,h));switch(typeof h){case "string":return m(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";l+=x;o=[];if(Object.prototype.toString.apply(h)==="[object Array]"){n=h.length;for(q=0;q<n;q+=1)o[q]=j(q,h)||"null";s=o.length===0?"[]":l?"[\n"+l+o.join(",\n"+l)+"\n"+p+"]":
"["+o.join(",")+"]";l=p;return s}if(t&&typeof t=="object"){n=t.length;for(q=0;q<n;q+=1)typeof t[q]=="string"&&(u=t[q],s=j(u,h),s&&o.push(m(u)+(l?": ":":")+s))}else for(u in h)Object.prototype.hasOwnProperty.call(h,u)&&(s=j(u,h),s&&o.push(m(u)+(l?": ":":")+s));s=o.length===0?"{}":l?"{\n"+l+o.join(",\n"+l)+"\n"+p+"}":"{"+o.join(",")+"}";l=p;return s}}function m(a){r.lastIndex=0;return r.test(a)?'"'+a.replace(r,function(a){var e=I[a];return typeof e=="string"?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function a(a){return a<10?"0"+a:a}typeof Date.prototype.toJSON!="function"&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var v=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
r=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,l,x,I={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},t;typeof JSON.stringify!="function"&&(JSON.stringify=function(a,m,q){var r;l="";x="";if(typeof q=="number")for(r=0;r<q;r+=1)x+=" ";else typeof q=="string"&&(x=q);t=m;if(!m||typeof m=="function"||typeof m=="object"&&typeof m.length=="number")return j("",{"":a});throw Error("JSON.stringify");
});typeof JSON.parse!="function"&&(JSON.parse=function(a,j){function m(a,e){var l,o,h=a[e];if(h&&typeof h=="object")for(l in h)Object.prototype.hasOwnProperty.call(h,l)&&(o=m(h,l),o!==void 0?h[l]=o:delete h[l]);return j.call(a,e,h)}var l;a=String(a);v.lastIndex=0;v.test(a)&&(a=a.replace(v,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return l=eval("("+a+")"),typeof j=="function"?m({"":l},""):l;throw new SyntaxError("JSON.parse");})})();
SockJS=function(){var j=document,m=window,a={},v=function(){};v.prototype.addEventListener=function(c,b){if(!this._listeners)this._listeners={};c in this._listeners||(this._listeners[c]=[]);var i=this._listeners[c];a.arrIndexOf(i,b)===-1&&i.push(b)};v.prototype.removeEventListener=function(c,b){if(this._listeners&&c in this._listeners){var i=this._listeners[c],f=a.arrIndexOf(i,b);f!==-1&&(i.length>1?this._listeners[c]=i.slice(0,f).concat(i.slice(f+1)):delete this._listeners[c])}};v.prototype.dispatchEvent=
function(c){var a=c.type,i=Array.prototype.slice.call(arguments,0);this["on"+a]&&this["on"+a].apply(this,i);if(this._listeners&&a in this._listeners)for(var f=0;f<this._listeners[a].length;f++)this._listeners[a][f].apply(this,i)};var r=function(c,a){this.type=c;if(typeof a!=="undefined")for(var i in a)a.hasOwnProperty(i)&&(this[i]=a[i])};r.prototype.toString=function(){var a=[],b;for(b in this)if(this.hasOwnProperty(b)){var i=this[b];typeof i==="function"&&(i="[function]");a.push(b+"="+i)}return"SimpleEvent("+
a.join(", ")+")"};var l=function(a){this.events=a||[]};l.prototype.emit=function(c){var b=Array.prototype.slice.call(arguments,1);!this.nuked&&this["on"+c]&&this["on"+c].apply(this,b);a.arrIndexOf(this.events,c)===-1&&a.log("Event "+JSON.stringify(c)+" not listed "+JSON.stringify(this.events)+" in "+this)};l.prototype.nuke=function(){this.nuked=!0;for(var a=0;a<this.events.length;a++)delete this[this.events[a]]};a.random_string=function(a,b){var b=b||37,i,f=[];for(i=0;i<a;i++)f.push("abcdefghijklmnopqrstuvwxyz0123456789_".substr(Math.floor(Math.random()*
b),1));return f.join("")};a.random_number=function(a){return Math.floor(Math.random()*a)};a.random_number_string=function(c){var b=(""+(c-1)).length;return(Array(b+1).join("0")+a.random_number(c)).slice(-b)};a.getOrigin=function(a){a+="/";return a.split("/").slice(0,3).join("/")};a.isSameOriginUrl=function(a,b){if(!b)b=m.location.href;return a.split("/").slice(0,3).join("/")===b.split("/").slice(0,3).join("/")};a.getParentDomain=function(a){return/^[0-9.]*$/.test(a)?a:/^\[/.test(a)?a:!/[.]/.test(a)?
a:a.split(".").slice(1).join(".")};a.objectExtend=function(a,b){for(var i in b)b.hasOwnProperty(i)&&(a[i]=b[i]);return a};a.polluteGlobalNamespace=function(){"_jp"in m||(m._jp={})};a.closeFrame=function(a,b){return"c"+JSON.stringify([a,b])};a.userSetCode=function(a){return a===1E3||a>=3E3&&a<=4999};a.countRTO=function(a){return a>100?3*a:a+200};a.log=function(){m.console&&console.log&&console.log.apply&&console.log.apply(console,arguments)};a.bind=function(a,b){return a.bind?a.bind(b):function(){return a.apply(b,
arguments)}};a.flatUrl=function(a){return a.indexOf("?")===-1&&a.indexOf("#")===-1};a.amendUrl=function(c){var b=j.location;if(!c)throw Error("Wrong url for SockJS");if(!a.flatUrl(c))throw Error("Only basic urls are supported in SockJS");c.indexOf("//")===0&&(c=b.protocol+c);c.indexOf("/")===0&&(c=b.protocol+"//"+b.host+c);return c=c.replace(/[/]+$/,"")};a.arrIndexOf=function(a,b){for(var i=0;i<a.length;i++)if(a[i]===b)return i;return-1};a.arrSkip=function(c,b){var i=a.arrIndexOf(c,b);return i===
-1?c.slice():c.slice(0,i).concat(c.slice(i+1))};a.isArray=Array.isArray||function(a){return{}.toString.call(a).indexOf("Array")>=0};a.delay=function(a,b){typeof a==="function"&&(b=a,a=0);return setTimeout(b,a)};var x=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,I={"\x00":"\\u0000","\u0001":"\\u0001","\u0002":"\\u0002","\u0003":"\\u0003","\u0004":"\\u0004","\u0005":"\\u0005","\u0006":"\\u0006","\u0007":"\\u0007","\u0008":"\\b",
"\t":"\\t","\n":"\\n","\u000b":"\\u000b","\u000c":"\\f","\r":"\\r","\u000e":"\\u000e","\u000f":"\\u000f","\u0010":"\\u0010","\u0011":"\\u0011","\u0012":"\\u0012","\u0013":"\\u0013","\u0014":"\\u0014","\u0015":"\\u0015","\u0016":"\\u0016","\u0017":"\\u0017","\u0018":"\\u0018","\u0019":"\\u0019","\u001a":"\\u001a","\u001b":"\\u001b","\u001c":"\\u001c","\u001d":"\\u001d","\u001e":"\\u001e","\u001f":"\\u001f",'"':'\\"',"\\":"\\\\","\u007f":"\\u007f","\u0080":"\\u0080","\u0081":"\\u0081","\u0082":"\\u0082",
"\u0083":"\\u0083","\u0084":"\\u0084","\u0085":"\\u0085","\u0086":"\\u0086","\u0087":"\\u0087","\u0088":"\\u0088","\u0089":"\\u0089","\u008a":"\\u008a","\u008b":"\\u008b","\u008c":"\\u008c","\u008d":"\\u008d","\u008e":"\\u008e","\u008f":"\\u008f","\u0090":"\\u0090","\u0091":"\\u0091","\u0092":"\\u0092","\u0093":"\\u0093","\u0094":"\\u0094","\u0095":"\\u0095","\u0096":"\\u0096","\u0097":"\\u0097","\u0098":"\\u0098","\u0099":"\\u0099","\u009a":"\\u009a","\u009b":"\\u009b","\u009c":"\\u009c","\u009d":"\\u009d",
"\u009e":"\\u009e","\u009f":"\\u009f","\u00ad":"\\u00ad","\u0600":"\\u0600","\u0601":"\\u0601","\u0602":"\\u0602","\u0603":"\\u0603","\u0604":"\\u0604","\u070f":"\\u070f","\u17b4":"\\u17b4","\u17b5":"\\u17b5","\u200c":"\\u200c","\u200d":"\\u200d","\u200e":"\\u200e","\u200f":"\\u200f","\u2028":"\\u2028","\u2029":"\\u2029","\u202a":"\\u202a","\u202b":"\\u202b","\u202c":"\\u202c","\u202d":"\\u202d","\u202e":"\\u202e","\u202f":"\\u202f","\u2060":"\\u2060","\u2061":"\\u2061","\u2062":"\\u2062","\u2063":"\\u2063",
"\u2064":"\\u2064","\u2065":"\\u2065","\u2066":"\\u2066","\u2067":"\\u2067","\u2068":"\\u2068","\u2069":"\\u2069","\u206a":"\\u206a","\u206b":"\\u206b","\u206c":"\\u206c","\u206d":"\\u206d","\u206e":"\\u206e","\u206f":"\\u206f","\ufeff":"\\ufeff","\ufff0":"\\ufff0","\ufff1":"\\ufff1","\ufff2":"\\ufff2","\ufff3":"\\ufff3","\ufff4":"\\ufff4","\ufff5":"\\ufff5","\ufff6":"\\ufff6","\ufff7":"\\ufff7","\ufff8":"\\ufff8","\ufff9":"\\ufff9","\ufffa":"\\ufffa","\ufffb":"\\ufffb","\ufffc":"\\ufffc","\ufffd":"\\ufffd",
"\ufffe":"\\ufffe","\uffff":"\\uffff"},t=/[\x00-\x1f\ud800-\udfff\ufffe\uffff\u0300-\u0333\u033d-\u0346\u034a-\u034c\u0350-\u0352\u0357-\u0358\u035c-\u0362\u0374\u037e\u0387\u0591-\u05af\u05c4\u0610-\u0617\u0653-\u0654\u0657-\u065b\u065d-\u065e\u06df-\u06e2\u06eb-\u06ec\u0730\u0732-\u0733\u0735-\u0736\u073a\u073d\u073f-\u0741\u0743\u0745\u0747\u07eb-\u07f1\u0951\u0958-\u095f\u09dc-\u09dd\u09df\u0a33\u0a36\u0a59-\u0a5b\u0a5e\u0b5c-\u0b5d\u0e38-\u0e39\u0f43\u0f4d\u0f52\u0f57\u0f5c\u0f69\u0f72-\u0f76\u0f78\u0f80-\u0f83\u0f93\u0f9d\u0fa2\u0fa7\u0fac\u0fb9\u1939-\u193a\u1a17\u1b6b\u1cda-\u1cdb\u1dc0-\u1dcf\u1dfc\u1dfe\u1f71\u1f73\u1f75\u1f77\u1f79\u1f7b\u1f7d\u1fbb\u1fbe\u1fc9\u1fcb\u1fd3\u1fdb\u1fe3\u1feb\u1fee-\u1fef\u1ff9\u1ffb\u1ffd\u2000-\u2001\u20d0-\u20d1\u20d4-\u20d7\u20e7-\u20e9\u2126\u212a-\u212b\u2329-\u232a\u2adc\u302b-\u302c\uaab2-\uaab3\uf900-\ufa0d\ufa10\ufa12\ufa15-\ufa1e\ufa20\ufa22\ufa25-\ufa26\ufa2a-\ufa2d\ufa30-\ufa6d\ufa70-\ufad9\ufb1d\ufb1f\ufb2a-\ufb36\ufb38-\ufb3c\ufb3e\ufb40-\ufb41\ufb43-\ufb44\ufb46-\ufb4e\ufff0-\uffff]/g,
e,z=JSON&&JSON.stringify||function(a){x.lastIndex=0;x.test(a)&&(a=a.replace(x,function(a){return I[a]}));return'"'+a+'"'},q=function(a){var b,i={},f=[];for(b=0;b<65536;b++)f.push(String.fromCharCode(b));a.lastIndex=0;f.join("").replace(a,function(a){i[a]="\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4);return""});a.lastIndex=0;return i};a.quote=function(a){a=z(a);t.lastIndex=0;if(!t.test(a))return a;e||(e=q(t));return a.replace(t,function(a){return e[a]})};var u="websocket,xdr-streaming,xhr-streaming,iframe-eventsource,iframe-htmlfile,xdr-polling,xhr-polling,iframe-xhr-polling,jsonp-polling".split(",");
a.probeProtocols=function(){for(var a={},b=0;b<u.length;b++){var i=u[b];a[i]=h[i]&&h[i].enabled()}return a};a.detectProtocols=function(a,b,i){var f={},k=[];b||(b=u);for(var d=0;d<b.length;d++){var e=b[d];f[e]=a[e]}var g=function(a){var c=a.shift();f[c]?k.push(c):a.length>0&&g(a)};i.websocket!==!1&&g(["websocket"]);f["xhr-streaming"]&&!i.null_origin?k.push("xhr-streaming"):f["xdr-streaming"]&&!i.cookie_needed&&!i.null_origin?k.push("xdr-streaming"):g(["iframe-eventsource","iframe-htmlfile"]);f["xhr-polling"]&&
!i.null_origin?k.push("xhr-polling"):f["xdr-polling"]&&!i.cookie_needed&&!i.null_origin?k.push("xdr-polling"):g(["iframe-xhr-polling","jsonp-polling"]);return k};a.createHook=function(){var c="a"+a.random_string(8);if(!("_sockjs_global"in m)){var b={};m._sockjs_global=function(a){a in b||(b[a]={id:a,del:function(){delete b[a]}});return b[a]}}return m._sockjs_global(c)};a.attachMessage=function(c){a.attachEvent("message",c)};a.attachEvent=function(a,b){typeof m.addEventListener!=="undefined"?m.addEventListener(a,
b,!1):(j.attachEvent("on"+a,b),m.attachEvent("on"+a,b))};a.detachMessage=function(c){a.detachEvent("message",c)};a.detachEvent=function(a,b){typeof m.addEventListener!=="undefined"?m.removeEventListener(a,b,!1):(j.detachEvent("on"+a,b),m.detachEvent("on"+a,b))};var s={},n=!1,p=function(){for(var a in s)s[a](),delete s[a]};a.attachEvent("unload",function(){n||(n=!0,p())});a.unload_add=function(c){var b=a.random_string(8);s[b]=c;n&&a.delay(p);return b};a.unload_del=function(a){a in s&&delete s[a]};
a.createIframe=function(c,b){var d=j.createElement("iframe"),f,k,e=function(){clearTimeout(f);try{d.onload=null}catch(a){}d.onerror=null},g=function(){d&&(e(),setTimeout(function(){d&&d.parentNode.removeChild(d);d=null},0),a.unload_del(k))},h=function(a){d&&(g(),b(a))};d.src=c;d.style.display="none";d.style.position="absolute";d.onerror=function(){h("onerror")};d.onload=function(){clearTimeout(f);f=setTimeout(function(){h("onload timeout")},2E3)};j.body.appendChild(d);f=setTimeout(function(){h("timeout")},
15E3);k=a.unload_add(g);return{post:function(a,c){try{d&&d.contentWindow&&d.contentWindow.postMessage(a,c)}catch(b){}},cleanup:g,loaded:e}};a.createHtmlfile=function(c,b){var d=new ActiveXObject("htmlfile"),f,k,e,g=function(){clearTimeout(f)},h=function(){d&&(g(),a.unload_del(k),e.parentNode.removeChild(e),e=d=null,CollectGarbage())};d.open();d.write('<html><script>document.domain="'+document.domain+'";<\/script></html>');d.close();d.parentWindow._jp=m._jp;var j=d.createElement("div");d.body.appendChild(j);
e=d.createElement("iframe");j.appendChild(e);e.src=c;f=setTimeout(function(){d&&(h(),b("timeout"))},15E3);k=a.unload_add(h);return{post:function(a,c){try{e&&e.contentWindow&&e.contentWindow.postMessage(a,c)}catch(b){}},cleanup:h,loaded:g}};var o=function(){};o.prototype=new l(["chunk","finish"]);o.prototype._start=function(c,b,d,f){var k=this;try{k.xhr=new XMLHttpRequest}catch(e){}if(!k.xhr)try{k.xhr=new m.ActiveXObject("Microsoft.XMLHTTP")}catch(g){}if(m.ActiveXObject||m.XDomainRequest)b+=(b.indexOf("?")===
-1?"?":"&")+"t="+ +new Date;k.unload_ref=a.unload_add(function(){k._cleanup(!0)});try{k.xhr.open(c,b,!0)}catch(h){k.emit("finish",0,"");k._cleanup();return}if(!f||!f.no_credentials)k.xhr.withCredentials="true";if(f&&f.headers)for(var j in f.headers)k.xhr.setRequestHeader(j,f.headers[j]);k.xhr.onreadystatechange=function(){if(k.xhr){var a=k.xhr;switch(a.readyState){case 3:try{var c=a.status,b=a.responseText}catch(d){}b&&b.length>0&&k.emit("chunk",c,b);break;case 4:k.emit("finish",a.status,a.responseText),
k._cleanup(!1)}}};k.xhr.send(d)};o.prototype._cleanup=function(c){if(this.xhr){a.unload_del(this.unload_ref);this.xhr.onreadystatechange=function(){};if(c)try{this.xhr.abort()}catch(b){}this.unload_ref=this.xhr=null}};o.prototype.close=function(){this.nuke();this._cleanup(!0)};(a.XHRCorsObject=function(){var c=this,b=arguments;a.delay(function(){c._start.apply(c,b)})}).prototype=new o;(a.XHRLocalObject=function(c,b,d){var f=this;a.delay(function(){f._start(c,b,d,{no_credentials:!0})})}).prototype=
new o;o=a.XDRObject=function(c,b,d){var f=this;a.delay(function(){f._start(c,b,d)})};o.prototype=new l(["chunk","finish"]);o.prototype._start=function(c,b,d){var f=this,k=new XDomainRequest;b+=(b.indexOf("?")===-1?"?":"&")+"t="+ +new Date;var e=k.ontimeout=k.onerror=function(){f.emit("finish",0,"");f._cleanup(!1)};k.onprogress=function(){f.emit("chunk",200,k.responseText)};k.onload=function(){f.emit("finish",200,k.responseText);f._cleanup(!1)};f.xdr=k;f.unload_ref=a.unload_add(function(){f._cleanup(!0)});
try{f.xdr.open(c,b),f.xdr.send(d)}catch(g){e()}};o.prototype._cleanup=function(c){if(this.xdr){a.unload_del(this.unload_ref);this.xdr.ontimeout=this.xdr.onerror=this.xdr.onprogress=this.xdr.onload=null;if(c)try{this.xdr.abort()}catch(b){}this.unload_ref=this.xdr=null}};o.prototype.close=function(){this.nuke();this._cleanup(!0)};a.isXHRCorsCapable=function(){return m.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest?1:m.XDomainRequest&&j.domain?2:A.enabled()?3:4};var h=function(c,b,d){var f=this,
k;f._options={devel:!1,debug:!1,protocols_whitelist:[],info:void 0,rtt:void 0};d&&a.objectExtend(f._options,d);f._base_url=a.amendUrl(c);f._server=f._options.server||a.random_number_string(1E3);f._options.protocols_whitelist&&f._options.protocols_whitelist.length?k=f._options.protocols_whitelist:(k=typeof b==="string"&&b.length>0?[b]:a.isArray(b)?b:null)&&f._debug('Deprecated API: Use "protocols_whitelist" option instead of supplying protocol list as a second parameter to SockJS constructor.');f._protocols=
[];f.protocol=null;f.readyState=h.CONNECTING;f._ir=P(f._base_url);f._ir.onfinish=function(c,b){f._ir=null;if(c){f._options.info&&(c=a.objectExtend(c,f._options.info));if(f._options.rtt)b=f._options.rtt;f._applyInfo(c,b,k);f._didClose()}else f._didClose(1002,"Can't connect to server",!0)}};h.prototype=new v;h.version="0.3.1";h.CONNECTING=0;h.OPEN=1;h.CLOSING=2;h.CLOSED=3;h.prototype._debug=function(){this._options.debug&&a.log.apply(a,arguments)};h.prototype._dispatchOpen=function(){if(this.readyState===
h.CONNECTING){if(this._transport_tref)clearTimeout(this._transport_tref),this._transport_tref=null;this.readyState=h.OPEN;this.dispatchEvent(new r("open"))}else this._didClose(1006,"Server lost session")};h.prototype._dispatchMessage=function(a){if(this.readyState===h.OPEN)switch(a=JSON.parse(a),a.op){case "ortc-validated":this.dispatchEvent(new r("ortcvalidated",{data:a.up,set:a.set}));break;case "ortc-subscribed":this.dispatchEvent(new r("ortcsubscribed",{data:a.ch}));break;case "ortc-unsubscribed":this.dispatchEvent(new r("ortcunsubscribed",
{data:a.ch}));break;case "ortc-error":this.dispatchEvent(new r("ortcerror",{data:a.ex}));break;default:this.dispatchEvent(new r("message",{data:a}))}};h.prototype._dispatchHeartbeat=function(){this.readyState===h.OPEN&&this.dispatchEvent(new r("heartbeat",{}))};h.prototype._didClose=function(c,b,d){var f=this;if(f.readyState!==h.CONNECTING&&f.readyState!==h.OPEN&&f.readyState!==h.CLOSING)throw Error("INVALID_STATE_ERR");if(f._ir)f._ir.nuke(),f._ir=null;if(f._transport)f._transport.doCleanup(),f._transport=
null;var k=new r("close",{code:c,reason:b,wasClean:a.userSetCode(c)});if(!a.userSetCode(c)&&f.readyState===h.CONNECTING&&!d){if(f._try_next_protocol(k))return;k=new r("close",{code:2E3,reason:"All transports failed",wasClean:!1,last_event:k})}f.readyState=h.CLOSED;a.delay(function(){f.dispatchEvent(k)})};h.prototype._didMessage=function(a){switch(a.slice(0,1)){case "o":this._dispatchOpen();break;case "a":for(var a=JSON.parse(a.slice(1)||"[]"),b=0;b<a.length;b++)this._dispatchMessage(a[b]);break;case "m":a=
JSON.parse(a.slice(1)||"null");this._dispatchMessage(a);break;case "c":a=JSON.parse(a.slice(1)||"[]");this._didClose(a[0],a[1]);break;case "h":this._dispatchHeartbeat()}};h.prototype._try_next_protocol=function(c){var b=this;if(b.protocol)b._debug("Closed transport:",b.protocol,""+c),b.protocol=null;if(b._transport_tref)clearTimeout(b._transport_tref),b._transport_tref=null;for(;;){c=b.protocol=b._protocols.shift();if(!c)return!1;if(h[c]&&h[c].need_body===!0&&(!j.body||typeof j.readyState!=="undefined"&&
j.readyState!=="complete"))return b._protocols.unshift(c),b.protocol="waiting-for-load",a.attachEvent("load",function(){b._try_next_protocol()}),!0;if(!h[c]||!h[c].enabled(b._options))b._debug("Skipping transport:",c);else{b._transport_tref=a.delay((b._options.rto||0)*(h[c].roundTrips||1)||5E3,function(){b.readyState===h.CONNECTING&&b._didClose(2007,"Transport timeouted")});var d=a.random_string(8),d=b._base_url+"/"+b._server+"/"+d;b._debug("Opening transport:",c," url:"+d," RTO:"+b._options.rto);
b._transport=new h[c](b,d,b._base_url);return!0}}};h.prototype.close=function(c,b){if(c&&!a.userSetCode(c))throw Error("INVALID_ACCESS_ERR");if(this.readyState!==h.CONNECTING&&this.readyState!==h.OPEN)return!1;this.readyState=h.CLOSING;this._didClose(c||1E3,b||"Normal closure");return!0};h.prototype.send=function(c){if(this.readyState===h.CONNECTING)throw Error("INVALID_STATE_ERR");this.readyState===h.OPEN&&this._transport.doSend(a.quote(""+c));return!0};h.prototype._applyInfo=function(c,b,d){this._options.info=
c;this._options.rtt=b;this._options.rto=a.countRTO(b);this._options.info.null_origin=!j.domain;b=a.probeProtocols();this._protocols=a.detectProtocols(b,d,c)};o=h.websocket=function(c,b){var d=this,f=b+"/websocket",f=f.slice(0,5)==="https"?"wss"+f.slice(5):"ws"+f.slice(4);d.ri=c;d.url=f;d.ws=new (m.WebSocket||m.MozWebSocket)(d.url);d.ws.onmessage=function(a){d.ri._didMessage(a.data)};d.unload_ref=a.unload_add(function(){d.ws.close()});d.ws.onclose=function(){d.ri._didMessage(a.closeFrame(1006,"WebSocket connection broken"))}};
o.prototype.doSend=function(a){this.ws.send("["+a+"]")};o.prototype.doCleanup=function(){var c=this.ws;if(c)c.onmessage=c.onclose=null,c.close(),a.unload_del(this.unload_ref),this.unload_ref=this.ri=this.ws=null};o.enabled=function(){return!(!m.WebSocket&&!m.MozWebSocket)};o.roundTrips=2;var y=function(){};y.prototype.send_constructor=function(a){this.send_buffer=[];this.sender=a};y.prototype.doSend=function(a){this.send_buffer.push(a);this.send_stop||this.send_schedule()};y.prototype.send_schedule_wait=
function(){var c=this,b;c.send_stop=function(){c.send_stop=null;clearTimeout(b)};b=a.delay(25,function(){c.send_stop=null;c.send_schedule()})};y.prototype.send_schedule=function(){var a=this;if(a.send_buffer.length>0){var b="["+a.send_buffer.join(",")+"]";a.send_stop=a.sender(a.trans_url,b,function(){a.send_stop=null;a.send_schedule_wait()});a.send_buffer=[]}};y.prototype.send_destructor=function(){this._send_stop&&this._send_stop();this._send_stop=null};var J=function(c,b,d){if(!("_send_form"in this)){var f=
this._send_form=j.createElement("form"),k=this._send_area=j.createElement("textarea");k.name="d";f.style.display="none";f.style.position="absolute";f.method="POST";f.enctype="application/x-www-form-urlencoded";f.acceptCharset="UTF-8";f.appendChild(k);j.body.appendChild(f)}var f=this._send_form,k=this._send_area,e="a"+a.random_string(8);f.target=e;f.action=c+"/jsonp_send?i="+e;var g;try{g=j.createElement('<iframe name="'+e+'">')}catch(h){g=j.createElement("iframe"),g.name=e}g.id=e;f.appendChild(g);
g.style.display="none";try{k.value=b}catch(m){a.log("Your browser is seriously broken. Go home! "+m.message)}f.submit();var l=function(){if(g.onerror)g.onreadystatechange=g.onerror=g.onload=null,a.delay(500,function(){g.parentNode.removeChild(g);g=null}),k.value="",d()};g.onerror=g.onload=l;g.onreadystatechange=function(){g.readyState=="complete"&&l()};return l},C=function(a){return function(b,d,f){(new a("POST",b+"/xhr_send",d)).onfinish=function(a){f(a)};return function(a){f(0,a)}}},G=function(c,
b){var d,f=j.createElement("script"),k,e=function(a){var i;k&&(k.parentNode.removeChild(k),k=null);if(f)clearTimeout(d),f.parentNode.removeChild(f),i=f.onreadystatechange=f.onerror=f.onload=f.onclick=null,f=i,b(a),b=null},g=!1,h=null;f.id="a"+a.random_string(8);f.src=c;f.type="text/javascript";f.charset="UTF-8";f.onerror=function(){h||(h=setTimeout(function(){g||e(a.closeFrame(1006,"JSONP script loaded abnormally (onerror)"))},1E3))};f.onload=function(){e(a.closeFrame(1006,"JSONP script loaded abnormally (onload)"))};
f.onreadystatechange=function(){if(/loaded|closed/.test(f.readyState)){if(f&&f.htmlFor&&f.onclick){g=!0;try{f.onclick()}catch(b){}}f&&e(a.closeFrame(1006,"JSONP script loaded abnormally (onreadystatechange)"))}};if(typeof f.async==="undefined"&&j.attachEvent)if(/opera/i.test(navigator.userAgent))k=j.createElement("script"),k.text="try{var a = document.getElementById('"+f.id+"'); if(a)a.onerror();}catch(x){};",f.async=k.async=!1;else{try{f.htmlFor=f.id,f.event="onclick"}catch(m){}f.async=!0}if(typeof f.async!==
"undefined")f.async=!0;d=setTimeout(function(){e(a.closeFrame(1006,"JSONP script loaded abnormally (timeout)"))},35E3);var l=j.getElementsByTagName("head")[0];l.insertBefore(f,l.firstChild);k&&l.insertBefore(k,l.firstChild);return e},o=h["jsonp-polling"]=function(c,b){a.polluteGlobalNamespace();this.ri=c;this.trans_url=b;this.send_constructor(J);this._schedule_recv()};o.prototype=new y;o.prototype._schedule_recv=function(){var a=this;a._recv_stop=R(a.trans_url+"/jsonp",G,function(b){a._recv_stop=
null;b&&(a._is_closing||a.ri._didMessage(b));a._is_closing||a._schedule_recv()})};o.enabled=function(){return!0};o.need_body=!0;o.prototype.doCleanup=function(){this._is_closing=!0;this._recv_stop&&this._recv_stop();this.ri=this._recv_stop=null;this.send_destructor()};var R=function(c,b,d){var f="a"+a.random_string(6),c=c+"?c="+escape("_jp."+f),b=b(c,function(a){delete m._jp[f];d(a)});m._jp[f]=b;return function(){if(m._jp[f])m._jp[f](a.closeFrame(1E3,"JSONP user aborted read"))}},o=function(){};o.prototype=
new y;o.prototype.run=function(a,b,d,f,k){this.ri=a;this.trans_url=b;this.send_constructor(C(k));this.poll=new K(a,f,b+d,k)};o.prototype.doCleanup=function(){if(this.poll)this.poll.abort(),this.poll=null};var w=h["xhr-streaming"]=function(c,b){this.run(c,b,"/xhr_streaming",d,a.XHRCorsObject)};w.prototype=new o;w.enabled=function(){return m.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&!/opera/i.test(navigator.userAgent)};w.roundTrips=2;w.need_body=!0;y=h["xdr-streaming"]=function(c,b){this.run(c,
b,"/xhr_streaming",d,a.XDRObject)};y.prototype=new o;y.enabled=function(){return!!m.XDomainRequest};y.roundTrips=2;var O=h["xhr-polling"]=function(c,b){this.run(c,b,"/xhr",d,a.XHRCorsObject)};O.prototype=new o;O.enabled=w.enabled;O.roundTrips=2;w=h["xdr-polling"]=function(c,b){this.run(c,b,"/xhr",d,a.XDRObject)};w.prototype=new o;w.enabled=y.enabled;w.roundTrips=2;var A=function(){};A.prototype.i_constructor=function(c,b,d){var f=this;f.ri=c;f.origin=a.getOrigin(d);f.base_url=d;f.trans_url=b;c=d+
"/iframe.html";f.ri._options.devel&&(c+="?t="+ +new Date);f.window_id=a.random_string(8);c+="#"+f.window_id;f.iframeObj=a.createIframe(c,function(a){f.ri._didClose(1006,"Unable to load an iframe ("+a+")")});f.onmessage_cb=a.bind(f.onmessage,f);a.attachMessage(f.onmessage_cb)};A.prototype.doCleanup=function(){if(this.iframeObj){a.detachMessage(this.onmessage_cb);try{this.iframeObj.iframe.contentWindow&&this.postMessage("c")}catch(c){}this.iframeObj.cleanup();this.onmessage_cb=this.iframeObj=this.iframeObj=
null}};A.prototype.onmessage=function(a){if(a.origin===this.origin){var b=a.data.slice(0,8),d=a.data.slice(8,9),a=a.data.slice(9);if(b===this.window_id)switch(d){case "s":this.iframeObj.loaded();this.postMessage("s",JSON.stringify([h.version,this.protocol,this.trans_url,this.base_url]));break;case "t":this.ri._didMessage(a)}}};A.prototype.postMessage=function(a,b){this.iframeObj.post(this.window_id+a+(b||""),this.origin)};A.prototype.doSend=function(a){this.postMessage("m",a)};A.enabled=function(){var a=
navigator&&navigator.userAgent&&navigator.userAgent.indexOf("Konqueror")!==-1;return(typeof m.postMessage==="function"||typeof m.postMessage==="object")&&!a};var B,F=function(c,b){parent!==m?parent.postMessage(B+c+(b||""),"*"):a.log("Can't postMessage, no parent window.",c,b)},D=function(){};D.prototype._didClose=function(c,b){F("t",a.closeFrame(c,b))};D.prototype._didMessage=function(a){F("t",a)};D.prototype._doSend=function(a){this._transport.doSend(a)};D.prototype._doCleanup=function(){this._transport.doCleanup()};
a.parent_origin=void 0;h.bootstrap_iframe=function(){var c;B=j.location.hash.slice(1);a.attachMessage(function(b){if(b.source===parent){if(typeof a.parent_origin==="undefined")a.parent_origin=b.origin;if(b.origin===a.parent_origin){var d=b.data.slice(0,8),f=b.data.slice(8,9),b=b.data.slice(9);if(d===B)switch(f){case "s":var k=JSON.parse(b),d=k[0],f=k[1],b=k[2],k=k[3];d!==h.version&&a.log('Incompatibile SockJS! Main site uses: "'+d+'", the iframe: "'+h.version+'".');if(!a.flatUrl(b)||!a.flatUrl(k)){a.log("Only basic urls are supported in SockJS");
break}if(!a.isSameOriginUrl(b)||!a.isSameOriginUrl(k)){a.log("Can't connect to different domain from within an iframe. ("+JSON.stringify([m.location.href,b,k])+")");break}c=new D;c._transport=new D[f](c,b,k);break;case "m":c._doSend(b);break;case "c":c&&c._doCleanup(),c=null}}}});F("s")};var H=function(c,b){var d=this;a.delay(function(){d.doXhr(c,b)})};H.prototype=new l(["finish"]);H.prototype.doXhr=function(){this.emit("finish",{websocket:!0,origins:["*:*"],cookie_needed:!1,entropy:+new Date},5E3)};
var L=function(c){var b=this,d=function(){var a=new A;a.protocol="w-iframe-info-receiver";var d=function(c){typeof c==="string"&&c.substr(0,1)==="m"?(c=JSON.parse(c.substr(1)),b.emit("finish",c[0],c[1])):b.emit("finish");a.doCleanup();a=null};a.i_constructor({_options:{},_didClose:d,_didMessage:d},c,c)};j.body?d():a.attachEvent("load",d)};L.prototype=new l(["finish"]);var N=function(){var c=this;a.delay(function(){c.emit("finish",{},5E3)})};N.prototype=new l(["finish"]);var P=function(c){if(a.isSameOriginUrl(c))return new H(c,
a.XHRLocalObject);switch(a.isXHRCorsCapable()){case 1:return new H(c,a.XHRCorsObject);case 2:return new H(c,a.XDRObject);case 3:return new L(c);default:return new N}};(D["w-iframe-info-receiver"]=function(c,b,d){(new H(d,a.XHRLocalObject)).onfinish=function(a,b){c._didMessage("m"+JSON.stringify([a,b]));c._didClose()}}).prototype.doCleanup=function(){};l=h["iframe-eventsource"]=function(){this.protocol="w-iframe-eventsource";this.i_constructor.apply(this,arguments)};l.prototype=new A;l.enabled=function(){return"EventSource"in
m&&A.enabled()};l.need_body=!0;l.roundTrips=3;(D["w-iframe-eventsource"]=function(c,b){this.run(c,b,"/eventsource",M,a.XHRLocalObject)}).prototype=new o;l=h["iframe-xhr-polling"]=function(){this.protocol="w-iframe-xhr-polling";this.i_constructor.apply(this,arguments)};l.prototype=new A;l.enabled=function(){return m.XMLHttpRequest&&A.enabled()};l.need_body=!0;l.roundTrips=3;(D["w-iframe-xhr-polling"]=function(c,b){this.run(c,b,"/xhr",d,a.XHRLocalObject)}).prototype=new o;l=h["iframe-htmlfile"]=function(){this.protocol=
"w-iframe-htmlfile";this.i_constructor.apply(this,arguments)};l.prototype=new A;l.enabled=function(){return A.enabled()};l.need_body=!0;l.roundTrips=3;(D["w-iframe-htmlfile"]=function(c,b){this.run(c,b,"/htmlfile",g,a.XHRLocalObject)}).prototype=new o;var K=function(a,b,d,f){this.ri=a;this.Receiver=b;this.recv_url=d;this.AjaxObject=f;this._scheduleRecv()};K.prototype._scheduleRecv=function(){var a=this,b=a.poll=new a.Receiver(a.recv_url,a.AjaxObject),d=0;b.onmessage=function(b){d+=1;a.ri._didMessage(b.data)};
b.onclose=function(d){var c;a.poll=(c=b.onmessage=b.onclose=null,b=c);a.poll_is_closing||(d.reason==="permanent"?a.ri._didClose(1006,"Polling error ("+d.reason+")"):a._scheduleRecv())}};K.prototype.abort=function(){this.poll_is_closing=!0;this.poll&&this.poll.abort()};var M=function(c){var b=this,d=new EventSource(c);d.onmessage=function(a){b.dispatchEvent(new r("message",{data:unescape(a.data)}))};b.es_close=d.onerror=function(c,k){var e=k?"user":d.readyState!==2?"network":"permanent";b.es_close=
d.onmessage=d.onerror=null;d.close();d=null;a.delay(200,function(){b.dispatchEvent(new r("close",{reason:e}))})}};M.prototype=new v;M.prototype.abort=function(){this.es_close&&this.es_close({},!0)};var E,g=function(c){var b=this;a.polluteGlobalNamespace();b.id="a"+a.random_string(6,26);c+=(c.indexOf("?")===-1?"?":"&")+"c="+escape("_jp."+b.id);if(E===void 0)if("ActiveXObject"in m)try{E=!!new ActiveXObject("htmlfile")}catch(d){}else E=!1;var e=E?a.createHtmlfile:a.createIframe,k;m._jp[b.id]={start:function(){k.loaded()},
message:function(a){b.dispatchEvent(new r("message",{data:a}))},stop:function(){b.iframe_close({},"network")}};b.iframe_close=function(a,c){k.cleanup();b.iframe_close=k=null;delete m._jp[b.id];b.dispatchEvent(new r("close",{reason:c}))};k=e(c,function(){b.iframe_close({},"permanent")})};g.prototype=new v;g.prototype.abort=function(){this.iframe_close&&this.iframe_close({},"user")};var d=function(a,b){var d=this,e=0;d.xo=new b("POST",a,null);d.xo.onchunk=function(a,b){if(a===200)for(;;){var c=b.slice(e),
g=c.indexOf("\n");if(g===-1)break;e+=g+1;c=c.slice(0,g);d.dispatchEvent(new r("message",{data:c}))}};d.xo.onfinish=function(a,b){d.xo.onchunk(a,b);d.xo=null;d.dispatchEvent(new r("close",{reason:a===200?"network":"permanent"}))}};d.prototype=new v;d.prototype.abort=function(){if(this.xo)this.xo.close(),this.dispatchEvent(new r("close",{reason:"user"})),this.xo=null};h.getUtils=function(){return a};h.getIframeTransport=function(){return A};return h}();
"_sockjs_onload"in window&&setTimeout(_sockjs_onload,1);typeof define==="function"&&define.amd&&define("sockjs",[],function(){return SockJS});
function IbtRealTimeSJ(){var j,m,a,v,r,l,x,I,t,e,z,q,u,s,n,p,o,h,y,J,C;a=5E3;connectionMetadataMaxSize=256;var G=15,R=3,w=!1;v={};n={};y=m=o=I=x=l=!1;e=this;h=q=p=null;J=void 0;this.getId=function(){return r};this.setId=function(a){r=a};this.getUrl=function(){return z};this.setUrl=function(a){z=a;j=null};this.getClusterUrl=function(){return j};this.setClusterUrl=function(a){j=a;z=null};this.getConnectionTimeout=function(){return a};this.setConnectionTimeout=function(b){a=b};this.getIsConnected=function(){return l&&
e.sockjs!=null};this.getConnectionMetadata=function(){return u};this.setConnectionMetadata=function(a){u=a};this.getAnnouncementSubChannel=function(){return s};this.setAnnouncementSubChannel=function(a){s=a};this.getProtocol=function(){return J};this.setProtocol=function(a){J=a};this.getSessionId=function(){return C};this.getHeartbeatTime=function(){return G};this.setHeartbeatTime=function(a){a&&!isNaN(a)?a>60||a<10?f(e,"Heartbeat time is out of limits - Min: 10 | Max: 60"):G=a:f(e,"Invalid heartbeat time "+
a)};this.getHeartbeatFails=function(){return R};this.setHeartbeatFails=function(a){a&&!isNaN(a)?a>6||a<1?f(e,"Heartbeat fails is out of limits - Min: 1 | Max: 6"):R=a:f(e,"Invalid heartbeat fails "+a)};this.getHeartbeatActive=function(){return w};this.setHeartbeatActive=function(a){w=a};this.onReconnected=this.onReconnecting=this.onException=this.onUnsubscribed=this.onSubscribed=this.onDisconnected=this.onConnected=null;this.connect=function(a,b){if(l)f(e,"Already connected");else if(!z&&!j)f(e,"URL and Cluster URL are null or empty");
else if(a)if(b)if(z&&!ortcIsValidUrl(z))f(e,"Invalid URL");else if(j&&!ortcIsValidUrl(j))f(e,"Invalid Cluster URL");else if(ortcIsValidInput(a))if(ortcIsValidInput(b))if(ortcIsValidInput(s))if(u&&u.length>connectionMetadataMaxSize)f(e,"Connection metadata size exceeds the limit of "+connectionMetadataMaxSize+" characters");else{e.appKey=a;e.authToken=b;x=!0;t=!1;B(self);j&&j!=null?(j=j.ortcTreatUrl(),M()):(z=z.ortcTreatUrl(),e.sockjs=c(z));if(j&&j!=null&&j.indexOf("/ssl")>=0||z&&z.indexOf("https")>=
0)y?e.getConnectionTimeout()<3E5?e.getConnectionTimeout()<3E4?e.setConnectionTimeout(3E4):e.setConnectionTimeout((e.getConnectionTimeout()+10)*1E3):(t=!0,A()):e.setConnectionTimeout(3E4);if(!e.reconnectIntervalId&&!t)e.reconnectIntervalId=setInterval(function(){t?A():(e.sockjs==null&&!m&&K(),p!=null&&p+35E3<(new Date).getTime()&&(p=null,l&&P()))},e.getConnectionTimeout())}else f(e,"Announcement Subchannel has invalid characters");else f(e,"Authentication Token has invalid characters");else f(e,"Application Key has invalid characters");
else f(e,"Authentication Token is null or empty");else f(e,"Application Key is null or empty")};this.subscribe=function(a,b,c){if(l)if(a)if(ortcIsValidInput(a))if(n[a]&&n[a].isSubscribing)f(e,"Already subscribing to the channel '"+a+"'");else if(n[a]&&n[a].isSubscribed)f(e,"Already subscribed to the channel '"+a+"'");else if(a.length>100)f(e,"Channel size exceeds the limit of 100 characters");else if(ortcIsValidBoolean(b))if(ortcIsFunction(c)){if(e.sockjs!=null){var d=a.indexOf(":"),g=a,h=null;d>
0&&(g=a.substring(0,d+1)+"*");q&&q!=null&&(h=q[g]?q[g]:q[a]);q&&q!=null&&!h?f(e,"No permission found to subscribe to the channel '"+a+"'"):(n[a]?(n[a].isSubscribing=!0,n[a].isSubscribed=!1,n[a].subscribeOnReconnected=b,n[a].onMessageCallback=c):n[a]={isSubscribing:!0,isSubscribed:!1,subscribeOnReconnected:b,onMessageCallback:c},e.sockjs.send("subscribe;"+e.appKey+";"+e.authToken+";"+a+";"+h))}}else f(e,"The argument 'onMessageCallback' must be a function");else f(e,"The argument 'subscribeOnReconnected' must be a boolean");
else f(e,"Channel has invalid characters");else f(e,"Channel is null or empty");else f(e,"Not connected")};this.unsubscribe=function(a){l?a?ortcIsValidInput(a)?!n[a]||n[a]&&!n[a].isSubscribed?f(e,"Not subscribed to the channel "+a):a.length>100?f(e,"Channel size exceeds the limit of 100 characters"):e.sockjs!=null&&e.sockjs.send("unsubscribe;"+e.appKey+";"+a):f(e,"Channel has invalid characters"):f(e,"Channel is null or empty"):f(e,"Not connected")};this.send=function(a,b){if(!l||e.sockjs==null)f(e,
"Not connected");else if(a)if(ortcIsValidInput(a))if(b)if(ortcIsString(b))if(a.length>100)f(e,"Channel size exceeds the limit of 100 characters");else{var c=a.indexOf(":"),d=a,g=null;c>0&&(d=a.substring(0,c+1)+"*");q&&q!=null&&(g=q[d]?q[d]:q[a]);if(q&&q!=null&&!g)f(e,"No permission found to send to the channel '"+a+"'");else{var c=[],d=N(8),h,i=800-a.length;for(h=0;h<b.length;h+=i){if(b.length<=i){c.push(b);break}b.substring(h,h+i)&&c.push(b.substring(h,h+i))}for(h=1;h<=c.length;h++)e.sockjs.send("send;"+
e.appKey+";"+e.authToken+";"+a+";"+g+";"+d+"_"+h+"-"+c.length+"_"+c[h-1])}}else f(e,"Message must be a string");else f(e,"Message is null or empty");else f(e,"Channel has invalid characters");else f(e,"Channel is null or empty")};this.disconnect=function(){A();F();n={};!l&&!o?f(e,"Not connected"):P()};this.isSubscribed=function(a){if(l)if(a)if(ortcIsValidInput(a))return n[a]&&n[a].isSubscribed?n[a].isSubscribed:!1;else f(e,"Channel has invalid characters");else f(e,"Channel is null or empty");else f(e,
"Not connected")};this.presence=function(a,c){try{var d=null,f=!1,g=e.appKey,h=e.authToken;a.url?(d=a.url.ortcTreatUrl(),f=a.isCluster,g=a.applicationKey,h=a.authenticationToken):j&&j!=null?(d=j,f=!0):d=z.ortcTreatUrl();O({requestUrl:d,isCluster:f,appKey:g},function(d,e){d?c(d,null):b(e+"/presence/"+g+"/"+h+"/"+a.channel,c)})}catch(i){c("Unable to get presence data",null)}};var O=function(a,b){if(a.requestUrl&&a.isCluster){var c=d(),e="guid="+d(),e=a.appKey?e+"&appkey="+a.appKey:e;g(a.requestUrl+
"/?"+e,c,function(a,c){a?b(null,SOCKET_SERVER):b(null,"Unable to get server from cluster");try{E(c)}catch(d){}})}else c=a.requestUrl.ortcTreatUrl(),b(null,c)},A=function(){if(e.reconnectIntervalId)clearInterval(e.reconnectIntervalId),e.reconnectIntervalId=null},B=function(a){if(a.validatedTimeoutId)clearTimeout(a.validatedTimeoutId),a.validatedTimeoutId=null},F=function(){t=!0;I=!1},D=function(a){if(!a.heartbeatInterval&&w)a.sockjs.send("b"),a.heartbeatInterval=setInterval(function(){w?a.sockjs.send("b"):
H(a)},G*1E3)},H=function(a){if(a.heartbeatInterval)clearInterval(a.heartbeatInterval),a.heartbeatInterval=null},L=function(a){a+="=";for(var b=document.cookie.split(";"),c=null,d=0;d<b.length;d++){for(var e=b[d];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(a)==0){c=e.substring(a.length,e.length);break}}return c},N=function(a){for(var b="",c=0;c<a/4;c++)b+=((1+Math.random())*65536|0).toString(16).substring(1);return b},P=function(){H(e);h=null;y=x=l=!1;B(self);if(e.sockjs!=null)e.sockjs.close(),
e.sockjs=null},K=function(){H(e);x&&f(e,"Unable to connect");x=!0;if(e!=null&&e.onReconnecting!=null)e.onReconnecting(e);h=(new Date).getTime();j&&j!=null?M():e.sockjs=c(z)},M=function(){var a=d(),b="guid="+d(),b=e.appKey?b+"&appkey="+e.appKey:b;g(j+"/?"+b,a,function(a,b){a&&(z=SOCKET_SERVER,c(e.getUrl()));try{E(b)}catch(d){}})},E=function(a){for(var b=document.getElementsByTagName("head")[0].children,c=[],d=0;d<b.length;d++)b[d].attributes!=null&&b[d].attributes.ortcScriptId&&b[d].attributes.ortcScriptId.value==
a&&c.push(d);for(var e in c)document.getElementsByTagName("head")[0].removeChild(b[c[e]])},g=function(a,b,c){var d=document.createElement("script");d.type="text/javascript";d.setAttribute("ortcScriptId",b);m=!0;d.readyState?d.onreadystatechange=function(){if(d.readyState=="loaded"||d.readyState=="complete")m=!1,d.onreadystatechange=null,typeof SOCKET_SERVER!="undefined"&&SOCKET_SERVER.indexOf("undefined")<0&&SOCKET_SERVER.indexOf("unknown_server")<0?c(!0,b):c(!1,b)}:d.onload=function(){m=!1;typeof SOCKET_SERVER!=
"undefined"&&SOCKET_SERVER.indexOf("undefined")<0&&SOCKET_SERVER.indexOf("unknown_server")<0?c(!0,b):c(!1,b)};d.onerror=function(){m=!1};d.src=a;document.getElementsByTagName("head")[0].appendChild(d)},d=function(){var a=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()},c=function(b){if(e.sockjs==null){navigator&&navigator.userAgent&&navigator.userAgent.indexOf("PlayStation Vita")>=0&&(J="jsonp-polling");e.sockjs=new SockJS(b+
"/broadcast",J);if(!e.sslFallback)e.validatedTimeoutId=setTimeout(function(){e.sslFallback=!0;F();P();y=o=!0;J=void 0;if(!("ActiveXObject"in window))if(j&&j!=null){if(j.indexOf("ssl/")<0){var a=j.search(/\/([\d.]*)\/$/);j=a>-1?j.substring(0,a+1)+"ssl/"+j.substring(a+1,j.length):j.substring(0,j.lastIndexOf("/")+1)+"ssl/"+j.substring(j.lastIndexOf("/")+1)}}else z=z.replace("http://","https://")},5E3);e.sockjs.onopen=function(){J=e.sockjs.protocol;p=(new Date).getTime();if(I)C="";else if(C=L("ortcsession-"+
e.appKey+"-s"),!C)(C=L("ortcsession-"+e.appKey))||(C=N(16)),document.cookie="ortcsession-"+e.appKey+"-s="+C+"; path=/",L("ortcsession-"+e.appKey+"-s")||(C="");var a=w?";"+e.getHeartbeatTime()+";"+e.getHeartbeatFails()+";":"";e.sockjs.send("validate;"+e.appKey+";"+e.authToken+";"+(s?s:"")+";"+C+";"+u+a)};e.sockjs.onclose=function(b){H(e);if(e.sockjs!=null)e.sockjs.close(),e.sockjs=null;q=null;b.code!=1E3?(l&&(x=l=!1,J=void 0,i(e)),t||(!h||h+a<(new Date).getTime())&&K()):o||(x=l=!1,J=void 0,i(e));y&&
(e.connect(e.appKey,e.authToken),y=!1);o=!1};e.sockjs.onmessage=function(a){p=(new Date).getTime();var b=a.data,a=b.ch,b=b.m,c=/^(\w[^_]*)_{1}(\d*)-{1}(\d*)_{1}([\s\S.]*)$/.exec(b),d=null,f=1,g=1,h=!1;c&&c.length>0&&(c[1]&&(d=c[1]),c[2]&&(f=c[2]),c[3]&&(g=c[3]),c[4]&&(b=c[4]));if(d){v[d]||(v[d]={});v[d][f]=b;var c=0,i;for(i in v[d])c++;c==g&&(h=!0)}else h=!0;if(h){if(d){b="";for(i=1;i<=g;i++)b+=v[d][i],delete v[d][i];delete v[d]}if(e!=null&&n[a]&&n[a].isSubscribed&&n[a].onMessageCallback!=null)n[a].onMessageCallback(e,
a,b)}};e.sockjs.onortcsubscribed=function(a){p=(new Date).getTime();a=a.data;if(n[a])n[a].isSubscribing=!1,n[a].isSubscribed=!0;if(e!=null&&e.onSubscribed!=null&&a!=null)e.onSubscribed(e,a)};e.sockjs.onortcunsubscribed=function(a){p=(new Date).getTime();a=a.data;if(n[a])n[a].isSubscribed=!1;if(e!=null&&e.onUnsubscribed!=null&&a!=null)e.onUnsubscribed(e,a)};e.sockjs.onheartbeat=function(){p=(new Date).getTime()};e.sockjs.onortcvalidated=function(a){var b=30;if(a.data)q=a.data;if(a.set)b=a.set;B(e);
x=y=!1;l=!0;h=null;if(C){if(!L("ortcsession-"+e.appKey+"-s"))document.cookie="ortcsession-"+e.appKey+"-s="+C+"; path=/";if(!L("ortcsession-"+e.appKey)){var a="ortcsession-"+e.appKey,c=C,d="";b&&(d=new Date,d.setTime(d.getTime()+b*6E4),d="; expires="+d.toGMTString());document.cookie=a+"="+c+d+"; path=/"}}if(I){var a={},f;for(f in n)n[f].subscribeOnReconnected==!0&&(n[f].isSubscribing||n[f].isSubscribed)?(n[f].isSubscribing=!0,n[f].isSubscribed=!1,c=f.indexOf(":"),b=f,d=null,c>0&&(b=f.substring(0,c+
1)+"*"),q&&q!=null&&(d=q[b]?q[b]:q[f]),e.sockjs.send("subscribe;"+e.appKey+";"+e.authToken+";"+f+";"+d)):a[f]=f;for(var g in a)delete n[g];v={};e!=null&&e.onReconnected!=null&&(D(e),e.onReconnected(e))}else I=!0,e!=null&&e.onConnected!=null&&(D(e),e.onConnected(e))};e.sockjs.onortcerror=function(a){p=(new Date).getTime();var b=a.data,a=b.op,c=b.ch,b=b.ex?b.ex:b;f(e,b);switch(a){case "validate":b.indexOf("busy")<0?(o=!0,B(e),y=!1,F()):(B(e),y=!1);break;case "subscribe":if(c&&n[c])n[c].isSubscribing=
!1;break;case "subscribe_maxsize":case "unsubscribe_maxsize":case "shutdown":B(e);y=!1;break;case "send_maxsize":if(c&&n[c])n[c].isSubscribing=!1;F()}}}return e.sockjs},b=function(a,b){var c=document.head?document.head:document.getElementsByTagName("head")[0],d=document.createElement("script"),e="ortcJsonp"+ +new Date,f=setTimeout(function(){try{b("Unable to get data",null),window[e]=void 0,delete window[e],c.removeChild(d)}catch(a){}},15E3);window[e]=function(a){clearTimeout(f);a.error?b(a.error,
null):b(null,a.content);try{window[e]=void 0,delete window[e],c.removeChild(d)}catch(g){}};d.setAttribute("src",a+"?callback="+e);c.appendChild(d)},i=function(a){if(a!=null&&a.onDisconnected!=null)a.onDisconnected(a)},f=function(a,b){if(a!=null&&a.onException!=null)a.onException(a,b)}};
